baseURL: http://anakinfoxe.com/
languageCode: en-us
title: Mostly about Tech
theme: PaperMod
module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod
disqusShortname: anakinfoxe
googleAnalytics: G-NXBJD7M5CQ
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
minify:
  disableXML: true
  minifyOutput: true
taxonomies:
  category: categories
  tag: tags
  series: series

params:
  env: production
  defaultTheme: auto
  showToc: true
  tocOpen: true
  showCodeCopyButtons: true
  showBreadCrumbs: true
  showPostNavLinks: true
  comments: true
  homeInfoParams:
    title: "Hi there \U0001F44B"
    content: >
      I'm Xing


      ğŸ  The Greater Seattle area


      ğŸ§‘â€ğŸ’» Engineer, Programmer


      ğŸ™‹ Tech, History, Finance


  socialIcons:
  - name: linkedin
    url: https://www.linkedin.com/in/anakinfoxe/
  editPost:
    url: https://github.com/AnakinFoxe/my-website/tree/master/content
    text: Suggest Changes
    appendFilePath: true

menu:
  main:
  - name: Tags
    url: tags/
    weight: 10
  - name: Archives
    url: archives/
    weight: 20

pygmentsUseClasses: true
markup:
  highlight:
    codeFences: true
    guessSyntax: false
    lineNos: true
    style: monokai

